const playlist = [
  "songs/05. Blue Noise - PacaPaca Passion.mp3",
  "songs/Aci-L.mp3",
  "songs/adaptor vs DRIVE. - 大和撫子 -Wild Dances- [Official].mp3",
  "songs/Aether Crest： Astral - void (Mournfinale) × 水野健治 ｜ Arcaea.mp3",
  "songs/Aiobahn +81 feat. KOTOKO - INTERNET OVERDOSE (Official Music Video) [Theme for NEEDY GIRL OVERDOSE].mp3",
  "songs/Ardent Gaff.mp3",
  "songs/BGA ｜ gmtn. (witch's slave) - Illegal Paradise.mp3",
  "songs/Blacklolita - [CRYSTAL_ACCESS] [CHUNITHM].mp3",
  "songs/BMS - AXION ⧸ 削除 (Magic Mash Man) ⧸ deadblue238 (New Genuine Magicial Girl).mp3",
  "songs/bpm160の練習曲 ⧸ Alice.【nanobeat】【TAKUMI³】【ChainBeeT】.mp3",
  "songs/Brightness.mp3",
  "songs/Camellia - Λzure Vixen [From CHUNITHM].mp3",
  "songs/Crolul&Rion - Finite.mp3",
  "songs/Cytus II - Hydra (With Akira Complex) ► HQ Vers. ► Hardcore⧸Eurobeat.mp3",
  "songs/DECO＊27 - ヴァンパイア feat. 初音ミク.mp3",
  "songs/Defection.mp3",
  "songs/Devastating Blaster.mp3",
  "songs/Devillic Sphere.mp3",
  "songs/Dual Fractal.mp3",
  "songs/Endless Seeker.mp3",
  "songs/Essence of Twilight.mp3",
  "songs/Forever Bound - Stereo Madness.mp3",
  "songs/Fracture Ray.mp3",
  "songs/Giga - '劣等上等'(BRING IT ON) ft.鏡音リン・レン【MV】.mp3",
  "songs/Giga × Mitchie M - ワーワーワールド feat. 初音ミク&鏡音リン（プロジェクトセカイ テーマ曲）.mp3",
  "songs/Halcyon.mp3",
  "songs/Infinity Heaven.mp3",
  "songs/JIGOKU STATION CENTRAL GATE (feat. 000).mp3",
  "songs/Laur - DANGEROOOOUS JUNGLE [From WACCA].mp3",
  "songs/Locus Of Control.mp3",
  "songs/luna blu.mp3",
  "songs/monochrome princess.mp3",
  "songs/Neru - ロストワンの号哭(Lost One's Weeping) feat. Kagamine Rin.mp3",
  "songs/Nostalgia - Tsukasa feat.三澤秋.mp3",
  "songs/Red Zone Full version MP3.mp3",
  "songs/REDALiCE feat. Nomiya Ayumi - Colors.mp3",
  "songs/rejection - Hypnotize【from ＂Arcaea＂】.mp3",
  "songs/Ringed Genesis.mp3",
  "songs/RiraN - Flashback 【maimai でらっくす】.mp3",
  "songs/Sakuzyo - グラウンドスライダー協奏曲第一番「風唄」【CHUNITHM】.mp3",
  "songs/Sakuzyo or Sobrem - Sweet & Sour [CHUNITHM X-VERSE-X].mp3",
  "songs/t+pazolite - You Are the Miserable.mp3",
  "songs/Taiko Warrior @ フリーBGM DOVA-SYNDROME OFFICIAL YouTube CHANNEL.mp3",
  "songs/TEmPTaTiON.mp3",
  "songs/Tsuki ni Murakumo Hana ni Kaze (Yuuhei Satellite).mp3",
  "songs/TVアニメ「機巧少女は傷つかない」EDテーマ「回レ! 雪月花」／歌組雪月花.mp3",
  "songs/ULTRA RENDA 1 ⧸ ルゼ.mp3",
  "songs/Vampire.mp3",
  "songs/virkato - ピアノ協奏曲第1番＂蠍火＂.mp3",
  "songs/We Gonna Journey.mp3",
  "songs/World Vanquisher.mp3",
  "songs/Yukopi - 寝起きヤシの木 (feat.歌愛ユキ).mp3",
  "songs/Zekk - Libertas [from Arcaea ⧸ Official Audio].mp3",
  "songs/[#G2R2018] EBIMAYO - GOODWORLD [BGA].mp3",
  "songs/[Amateras Records] Unrequited Hearts #03 - Lonly Ranunculus.mp3",
  "songs/[Arcaea] crayvxn - Saint or Sinner.mp3",
  "songs/[BMS] SHIKI - Air.mp3",
  "songs/[BMS]Angel dust ⧸ LV.4.mp3",
  "songs/[BOFU2017] Tanchiky - ENERGY SYNERGY MATRIX [BGA].mp3",
  "songs/[CHUNITHM] Yuta Imai - Acid God.mp3",
  "songs/[from - Arcaea] Antagonism ⧸ Yooh vs. siromaru.mp3",
  "songs/[from - オンゲキR.E.D. PLUS] Adverse Gaff ⧸ siromaru.mp3",
  "songs/[From CHUNITHM] Yooh - Elemental Ethnic [Official Audio].mp3",
  "songs/[From Rotaeno] Yooh - Secret Illumination [Official Audio].mp3",
  "songs/[maimai pv] Revive The Rave.mp3",
  "songs/[MV] conflict ⧸ siromaru + cranky.mp3",
  "songs/[Official Audio] Crossmythos Rhapsodia ⧸ Acotto vs Potwi  ｜ CHUNITHM.mp3",
  "songs/[Official] BlackY a.k.a. WAiKURO survive - Divide et impera! [from maimai でらっくす].mp3",
  "songs/[Official] BlackY VS 大国奏音 - MegiddØ [from CHUNITHM].mp3",
  "songs/[Official] kanone vs. BlackY - Stardust：RAY [from オンゲキ].mp3",
  "songs/[Official] 炉心融解 feat.鏡音リン  ⧸  Meltdown feat.Kagamine Rin.mp3",
  "songs/[PABAT! 2017] Roy Mikelate - Now Is The Time, Do It.mp3",
  "songs/[Phigros] Apocalyptic - Z ClaxX & SumaiLight【音源】 【高音質】.mp3",
  "songs/[Phigros] Compute It With Some Devilish Alcholic Steampunk Engines - かめりあ【Music】.mp3",
  "songs/[Phigros] JunXion Between Life And Death(VIP Mix) - 1N6Fs【音源】 【高音質】.mp3",
  "songs/[Phigros] PTB10 - modulus.mp3",
  "songs/[東方vocal] Prominence [SoundOnline].mp3",
  "songs/【BMS】 ★LittlE HearTs★ 【音源】.mp3",
  "songs/【BMS】真・千年女王⧸Shiraishi【BGM】.mp3",
  "songs/【BOF2012】 HAELEQUIN 【BGA】.mp3",
  "songs/【CHUNITHM】Chaotic Ørder ⧸ TAG VS Kai.mp3",
  "songs/【from Arcaea】ryhki - In Vain (Official Audio).mp3",
  "songs/【G2R2018】energy trixxx ⧸ KAH【BGA】.mp3",
  "songs/【Hatsune Miku】 World is Mine ⧸ ryo（supercell）【初音ミク】.mp3",
  "songs/【maimai でらっくす】BREaK! BREaK! BREaK! ⧸ HiTECH NINJA vs Cranky【3⧸18(木)登場！】.mp3",
  "songs/【maimai でらっくす】ウタヒメナイトストーム ⧸ yowanecity feat.Eye【3⧸13(木)登場！】.mp3",
  "songs/【maimai】Alea jacta est!⧸BlackY fused with WAiKURO.mp3",
  "songs/【maimai】Oshama Scramble!⧸t+pazolite.mp3",
  "songs/【TAKUMI³】電脳戦姫-cyber valkyrie- - Rapidsystem【音源】.mp3",
  "songs/【オンゲキ⧸maimai⧸D4DJ⧸CHUNITHM】kanone - Falsum Atlantis.【音源】.mp3",
  "songs/【チュウニズム】神鳴 ⧸ Rígr feat. 光吉猛修.mp3",
  "songs/【公式】【東方Vocal】少女フラクタル ⧸ トロイメライ（原曲：ハルトマンの妖怪少女＆U.N.オーエンは彼女なのか？）【FullMV】.mp3",
  "songs/【公式】【東方Vocal】少女フラクタル ⧸ 彷徨いの冥～天～【FullMV】（原曲：幽雅に咲かせ、墨染の桜 ～ Border of Life）.mp3",
  "songs/【公式】【東方Vocal】幽閉サテライト ⧸ 月に叢雲華に風／歌唱：senya）【FullMV】（原曲：ラストリモート）.mp3",
  "songs/【公式】【東方Vocal】幽閉サテライト ⧸ 果てなき風の軌跡さえ～破～(歌唱senya&Marcia）【FullMV】（原曲：信仰は儚き人間の為に）【幻想万華鏡14話EDテーマ】.mp3",
  "songs/【公式】美夜月鏡 ⧸ かゆき [from オンゲキR.E.D.].mp3",
  "songs/【公式音源】Blazing：Storm [from CHUNITHM].mp3",
  "songs/【東方MV】taboo tears you up【IOSYS】.mp3",
  "songs/【東方MV】患部で止まってすぐ溶ける～狂気の優曇華院【IOSYS】.mp3",
  "songs/【東方MV】最速最高シャッターガール【ビートまりお】.mp3",
  "songs/【東方】 仙酌絶唱のファンタジア - 博麗神社例大祭コラボユニット.mp3",
  "songs/【東方ボーカルENG SUB】Scream Out!【A-ONE】.mp3",
  "songs/【東方ヴォーカルPV】待チ人ハ来ズ。【豚乙女公式】.mp3",
  "songs/【東方ヴォーカル】 取り残された美術 【幽閉サテライト】.mp3",
  "songs/ぴーなた-求＆影(Q&A) 重音テト.mp3",
  "songs/ももいろの鍵 ⧸ いよわ feat.初音ミク（The Peachy Key ⧸ Iyowa feat.Hatsune Miku）.mp3",
  "songs/アダチ・レイ ⧸ アダチ・レイ（CV：足立レイ）、重音テト（CV：重音テト）.mp3",
  "songs/イロドリミドリ 箱部なる（cv：M・A・O） 『猫祭り』MV.mp3",
  "songs/キャットラビング ⧸ 香椎モイミ feat. 可不.mp3",
  "songs/モエチャッカファイア ⧸ 弌誠：MUSIC VIDEO.mp3",
  "songs/ループザルーム feat. 初音ミク ⧸ ＂Looping the Rooms＂ ft. Hatsune Miku.mp3",
  "songs/八王子P 「気まぐれメルシィ  feat. 初音ミク」(6⧸15発売Best AL「Eight」収録）.mp3",
  "songs/好きな惣菜発表ドラゴン ⧸ 重音テト.mp3",
  "songs/宿星審判.mp3",
  "songs/東方原曲   妖々夢　PHANTASMボス・八雲 紫のテーマ　ネクロファンタジア.mp3",
  "songs/東方原曲　地霊殿　１面ボス黒谷 ヤマメ　封じられた妖怪　～ Lost Place.mp3",
  "songs/東方原曲　地霊殿　２面ボス水橋パルスィ　緑眼のジェラシー.mp3",
  "songs/東方原曲　地霊殿　５面ボス火焔猫 燐　死体旅行　～ Be of good cheer!.mp3",
  "songs/東方原曲　文花帖　撮影曲１　風の循環　～ Wind Tour.mp3",
  "songs/東方原曲　永夜抄　EXTRAボス藤原 妹紅のテーマ　月まで届け、不死の煙.mp3",
  "songs/東方原曲　永夜抄　２面ボスミスティアテーマ　もう歌しか聞こえない.mp3",
  "songs/東方原曲　緋想天　「全人類の緋想天」　幼心地の有頂天.mp3",
  "songs/東方原曲　風神録　EXTRAボス洩矢諏訪子テーマ　ネイティブフェイス.mp3",
  "songs/東方原曲　風神録　１面ボス秋 穣子のテーマ　稲田姫様に叱られるから.mp3",
  "songs/業 -善なる神とこの世の悪について-.mp3",
  "songs/私立BEMANI学園 ▪ Elemental Creation ▪ dj TAKA meets DJ YOSHITAKA.mp3",
  "songs/篠螺悠那 feat. 鯛の小骨 - Imperishable Night 2006.mp3",
  "songs/脳漿炸裂ガール - れるりりfeat.初音ミク&GUMI ⧸ Brain Fluid Explosion Girl - rerulili feat.miku&gumi.mp3",
  "songs/虚空の夢.mp3",
  "songs/＂神威＂ - TJ.hangneil  ⧸ Kamui.mp3",
];